# Generated by Django 3.0.5 on 2020-04-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signUpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('pin', models.CharField(max_length=7)),
            ],
        ),
    ]
