# Generated by Django 3.0.5 on 2020-04-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200409_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='mobile',
            new_name='phone',
        ),
    ]
