# Generated by Django 3.0 on 2020-04-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_likedlistings'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedlistings',
            name='likes',
            field=models.BooleanField(default=False),
        ),
    ]
