# Generated by Django 3.0 on 2020-04-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_likedlistings_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedlistings',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
