# Generated by Django 3.0.5 on 2020-04-09 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.CharField(choices=[('MTL', 'Montreal'), ('TOR', 'Toronto')], max_length=3)),
                ('state', models.CharField(max_length=50)),
                ('zipCode', models.CharField(max_length=10)),
                ('building_type', models.CharField(choices=[('AB', 'Apartment Building'), ('H', 'House'), ('B', 'Basement')], max_length=2)),
                ('garage', models.BooleanField(default=False)),
                ('space_given', models.CharField(choices=[('SR', 'Shared Room'), ('PB', 'Private bedroom'), ('EP', 'Entire Apartment/House')], max_length=2)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('image1', models.ImageField(default='default.jpeg', upload_to='photos/%Y%m%d/')),
                ('image2', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('image3', models.ImageField(blank=True, upload_to='photos/%Y%mb%d/')),
                ('image4', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('image5', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('image6', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('image7', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('image8', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('image9', models.ImageField(blank=True, upload_to='photos/%Y%mb%d/')),
                ('image10', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('image11', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('image12', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('bathrooms', models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                ('electricityIncluded', models.BooleanField(default=True)),
                ('wifiIncluded', models.BooleanField(default=False)),
                ('animalsAllowed', models.BooleanField(default=True)),
                ('furnished', models.TextField(choices=[('NF', 'NOT FURNISHED'), ('FF', 'FULLY FURNISHED'), ('SF', 'SEMI-FURNISHED')], default='NF')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
