# Generated by Django 3.0.5 on 2020-04-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('discription', models.CharField(max_length=20000)),
                ('price', models.FloatField(max_length=10)),
                ('location', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=10)),
                ('extra1', models.CharField(max_length=50)),
                ('extra2', models.CharField(max_length=30)),
                ('extra3', models.CharField(max_length=20)),
                ('extra4', models.CharField(max_length=10)),
            ],
        ),
    ]
