# Generated by Django 3.0.5 on 2020-04-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselistings',
            name='image',
            field=models.CharField(default='../images/default.jpeg', max_length=2085),
        ),
    ]
