# Generated by Django 3.0.5 on 2020-04-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselistings',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=1, default=3.5, max_digits=2),
        ),
        migrations.AlterField(
            model_name='houselistings',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, default=2, max_digits=2),
        ),
    ]
