# Generated by Django 3.0.5 on 2020-04-05 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_houselistings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselistings',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
