# Generated by Django 3.0.5 on 2020-04-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200409_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houselistings',
            name='state',
        ),
        migrations.AlterField(
            model_name='houselistings',
            name='animalsAllowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='houselistings',
            name='electricityIncluded',
            field=models.BooleanField(default=False),
        ),
    ]
