# Generated by Django 3.0.5 on 2020-04-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_houselistings_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houselistings',
            name='created_date',
        ),
    ]
